name: "Askar"

permissions:
  actions: write
  contents: write

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      publish:
        description: "Publish wrapper to NPM"
        required: true
        default: false
        type: boolean

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install
        run: pnpm install

      - name: Lint
        run: pnpm lint

      - name: build
        run: pnpm build

      - name: types
        run: pnpm types:check

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Test
        env:
          LIB_ASKAR_PATH: TODO
        run: pnpm test

  publish:
    runs-on: ubuntu-latest

    if: github.event_name == 'workflow_dispatch' && github.event.inputs.publish == 'true'

    steps:
      - name: Set NPM config
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" >> .npmrc
          echo "registry=https://registry.npmjs.org/" >> .npmrc
          echo "always-auth=true" >> .npmrc

      - name: Publish JavaScript Wrapper
        run: |
          if [[ $(cat lerna.json | grep version | head -1 | grep dev) ]]; then
            npx lerna publish from-package --no-push --no-private --yes --no-git-tag-version --dist-tag=alpha
          else
            npx lerna publish from-package --no-push --no-private --yes --no-git-tag-version
          fi
